version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
services: mssql2014
before_build:
- cmd: nuget restore
build:
  project: Pulse.sln
  verbosity: normal
after_build:
- ps: nuget pack Pulse.Core.nuspec -version "$env:buildVersion"
test: off
artifacts:
- path: Pulse.Core
  name: Pulse.Core
- path: Pulse.SqlStorage
  name: Pulse.SqlStorage
deploy:
- provider: NuGet
  api_key:
    secure: n2kyE7iymNnA4v4Xwg8wYKGb4VmPBwrdA0UDLaXIlcNUJDqV0o+1MoZYnqqvtw3M
  artifact: /.*\.nupkg/
  on:
    branch: master
notifications:
- provider: Email
  to:
  - vedran.vucetic@gmail.com
  subject: Build result
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true