version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
services: mssql2014
build:
  project: Pulse.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: YKKGGuDaZrjpiG0uAhelmYtuOs1Y6YbCzz/ThuojT3TCzTIqf2PnwajT1eFEsbQx
  on:
    branch: master
notifications:
- provider: Email
  to:
  - vedran.vucetic@gmail.com
  subject: Build result
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true